feat: add ci for windows arm64

diff --git a/.github/workflows/build-windows.yml b/.github/workflows/build-windows.yml
--- a/.github/workflows/build-windows.yml
+++ b/.github/workflows/build-windows.yml
@@ -16,6 +16,8 @@ jobs:
         include:
           - runner: sdk-windows-8-core-2
             arch: x86_64
+          - runner: windows-11-arm
+            arch: arm64
 
     steps:
       - name: Checkout repository
@@ -31,16 +33,57 @@ jobs:
           $shortHash = "${{ github.sha }}".Substring(0, 7)
           echo "VERSION=$shortHash" >> $env:GITHUB_ENV
 
+      - name: Figure Environment
+        run: |
+          which clang ||  echo "Clang not found"
+          which gcc || echo "GCC not found"
+          which dotnet || echo ".NET not found"
+          which go || echo "Go not found"
+          go env || echo "Go environment not found"
+
       - name: Setup Go
         uses: actions/setup-go@v5
         with:
           go-version: 1.24.3
           cache-dependency-path: runner/go.sum
 
-      - name: Setup MinGW
+      - name: Setup MSYS2 for ARM64
+        if: matrix.arch == 'arm64'
+        uses: msys2/setup-msys2@v2
+        with:
+          msystem: CLANGARM64
+          update: true
+          pacman: >-
+            mingw-w64-clang-aarch64-clang
+            mingw-w64-clang-aarch64-lld
+
+
+      - name: Verify Clang Installation
+        shell: msys2 {0}
         run: |
-          choco install mingw -y
-          g++ --version
+          which clang
+          echo "--- Verifying Clang compiler ---"
+          clang --version
+
+          echo "--- Verifying Clang++ compiler ---"
+          clang++ --version
+
+          echo "--- Verifying linker ---"
+          lld --version
+
+          echo "--- Checking PATH ---"
+          echo "$PATH"
+
+      - name: Setup ARM64 Environment
+        if: matrix.arch == 'arm64'
+        shell: bash
+        run: |
+          which clang || echo "Clang not found"
+          go env
+          echo "CGO_ENABLED=1" >> $GITHUB_ENV
+          echo "GOARCH=arm64" >> $GITHUB_ENV
+          echo "CC=clang" >> $GITHUB_ENV
+          echo "CXX=clang++" >> $GITHUB_ENV
 
       - name: Download runtime
         run: |
@@ -71,6 +114,8 @@ jobs:
         include:
           - runner: sdk-windows-8-core-2
             arch: x86_64
+          - runner: windows-11-arm
+            arch: arm64
     env:
       VERSION: ${{ github.ref_name }}
       ARCH: ${{ matrix.arch }}
@@ -118,16 +163,6 @@ jobs:
               -td sha256 `
               $_.FullName
           }
-
-          azuresigntool sign `
-            -kvu "${{ secrets.AZURE_KEY_VAULT_URI }}" `
-            -kvc "${{ secrets.AZURE_CERT_NAME }}" `
-            -kvi "${{ secrets.AZURE_CLIENT_ID }}" `
-            -kvs "${{ secrets.AZURE_CLIENT_SECRET }}" `
-            --azure-key-vault-tenant-id "${{ secrets.AZURE_TENANT_ID }}" `
-            -tr http://timestamp.globalsign.com/tsa/advanced `
-            -td sha256 `
-            "artifacts\nexa-cli-launcher.exe"
 
       - name: Compile Installer
         uses: Minionguyjpro/Inno-Setup-Action@v1.2.6
